name = "nodemailer-resend"
main = "./dist/worker.js"
compatibility_date = "2025-02-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "esbuild ./worker.js --bundle --format=esm --platform=node --outfile=dist/worker.js --external:express --external:cors --external:dotenv --external:express-rate-limit --external:formdata-node --external:node-fetch --external:nodemailer --external:resend"
watch_dir = "."

[vars]
NODE_ENV = "development"
PORT = "3001"

# Example of how to set up environment variables

# [vars.development]
# RESEND_API_KEY = "your_test_key_here"

# [vars.production]
# RESEND_API_KEY = "your_production_key_here"

[[rules]]
type = "ESModule"
globs = ["**/*.js"] 
