name = "email-router-demo"
main = "./dist/worker.js"
compatibility_date = "2024-02-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
node_compat = true

[build]
command = "npm run build"
watch_dir = "."

[vars]
NODE_ENV = "development"
PORT = "3001"

# Example of how to set up environment variables

# [vars.development]
# RESEND_API_KEY = "your_test_key_here"

# [vars.production]
# RESEND_API_KEY = "your_production_key_here"

[[rules]]
type = "ESModule"
globs = ["**/*.js"] 